; OPTIONAL "SEXY" ALIASES

define cpu intel windows
CD fix '../..'

include 'a.inc'

True  fix true
False fix false

Let   fix let
Go    fix go
Try   fix try
Catch fix catch

Byte	fix byte
Char	fix char
UChar	fix uchar
Short	fix short
UShort	fix ushort
Void	fix void
Pointer fix void
Int	fix integer
Integer fix integer
Long	fix long
ULong	fix ulong
Float	fix float
Double	fix double
Text	fix text

If	fix if
Else	fix else
ElseIf	fix else.if
End	fix end
EndIf	fix end

While	fix while
EndW	fix endw
Loop	fix loop
EndL	fix endl

Function fix function
Locals	 fix locals
EndF	 fix endf
Return	 fix return

; Event OnDraw ... EndE

Event fix function
EndE  fix endf

OnCreate fix on.create
OnDraw	 fix on.draw
OnKey	 fix on.key
OnMouse  fix on.mouse
OnTimer  fix on.timer
OnExit	 fix on.exit

; TEXT

TextZero    fix text.zero
TextEnd     fix text.end
TextN	    fix text.n
TextCopy    fix text.copy
TextCopyN   fix text.copy.n
TextAttach  fix text.attach
TextAttachC fix text.attach.c
TextCompare fix text.compare
TextEqual   fix text.equal
TextSearch  fix text.search
TextFind    fix text.find
TextFindR   fix text.find.r
TextCountC  fix text.count.c
TextCountW  fix text.count.w
TextCountN  fix text.count.n
TextGo	    fix text.go
TextUpper   fix text.upper
TextLower   fix text.lower
TextReverse fix text.reverse
TextBegins  fix text.begins
TextEnds    fix text.ends
TextSkip0   fix text.skip.0
TextShiftL  fix text.shift.l
TextShiftLA fix text.shift.la
TextExpand  fix text.expand
TextAlign   fix text.align